spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learnQuartz?characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: learnQuartzUser
    password: learnQuartzPassword

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
